### ISSUE TITLE
美丽研究院 自动运行build报错

### ISSUE THREAD

**Issue by dingxinyang** [inoyna11/jd28#96]
我添加了两个必填的secrets和一个非必填的推送secrets，运行后报找不到模块
```
internal/modules/cjs/loader.js:888``
  throw err;
  ^

Error: Cannot find module 'ws'
Require stack:
- /home/runner/work/jb_618/jb_618/jd_beauty.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/runner/work/jb_618/jb_618/jd_beauty.js:13:19)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/runner/work/jb_618/jb_618/jd_beauty.js' ]
}
Error: Process completed with exit code 1.
```

**Comment by inoyna11** [comment]
> 我添加了两个必填的secrets和一个非必填的推送secrets，运行后报找不到模块
> 
> ```
> internal/modules/cjs/loader.js:888``
>   throw err;
>   ^
> 
> Error: Cannot find module 'ws'
> Require stack:
> - /home/runner/work/jb_618/jb_618/jd_beauty.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:730:27)
>     at Module.require (internal/modules/cjs/loader.js:957:19)
>     at require (internal/modules/cjs/helpers.js:88:18)
>     at Object.<anonymous> (/home/runner/work/jb_618/jb_618/jd_beauty.js:13:19)
>     at Module._compile (internal/modules/cjs/loader.js:1068:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
>     at Module.load (internal/modules/cjs/loader.js:933:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:774:14)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [ '/home/runner/work/jb_618/jb_618/jd_beauty.js' ]
> }
> Error: Process completed with exit code 1.
> ```

这个脚本我先删了，等更新好加进去
